import type { Metadata } from "next";
import { Poppins, Roboto } from "next/font/google";
import { Toaster } from "sonner";
import { cn } from "@/lib/utils";
import "./globals.css";
import SiteHeader from "@/components/shared/header";
import SiteFooter from "@/components/shared/footer";

const poppins = Poppins({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body className={cn("antialiased", poppins.className, roboto.variable)}>
        <main className="flex min-h-screen flex-col">
          <SiteHeader />
          <Toaster richColors position="top-right" />
          <div>{children}</div>
          <SiteFooter />
        </main>
      </body>
    </html>
  );
}
